server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
      - id: user-service
        uri: lb://USER-SERVICE
        predicates:
        - Path=/users/**
        filters:
        - AddRequestHeader=X-Request-Source, API-Gateway
      - id: order-service
        uri: lb://ORDER-SERVICE
        predicates:
        - Path=/orders/**
        filters:
        - AddRequestHeader=X-Request-Source, API-Gateway